### ISSUE TITLE
initialFields causes react-unknown-prop error

### ISSUE THREAD

**Issue by kalongthewires** [rofrischmann/react-controlled-form#23]
Adding `initialFields` to `Form` causes the following error:

```
proxyConsole.js:56 Warning: Unknown prop initialFields on <form> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
    in form (created by Form)
    in Form (created by Connect(Form))
    etc.
```

It looks like other values that should not be passed down to `form` as props are removed (L131-139 of Form.js) but `initialFields` is not.

**Comment by robinweser** [comment]
Looks like I forgot that! Would you like to send a PR adding it?
