### ISSUE TITLE
TypeScript type definitions

### ISSUE THREAD

**Issue by dlindenkreuz** [rofrischmann/react-controlled-form#24]
Currently, this library is not usable with TypeScript. Does it make sense to add a definition file to this project? I'd be happy to work on a `.d.ts` file and send in a pull request.

**Comment by robinweser** [comment]
I'd really recommend any help here =) I am not using TypeScript myself.

**Comment by dlindenkreuz** [comment]
Alrighty, I'm currently working on the definition file. I'mma send in a pull request as soon as everything works.

**Comment by robinweser** [comment]
Still open to send a PR? Will close this issue for now as I personally don't need TypeScript definitions anyways, but feel free to reopen and add em :)
