### ISSUE TITLE
Accept undefined field values

### ISSUE THREAD

**Issue by dlindenkreuz** [rofrischmann/react-controlled-form#27]
https://github.com/rofrischmann/react-controlled-form/blob/0260db7b8199708695ba5ce6e1d0d949d79ffe66/modules/utils/composeFieldData.js#L7-L18

I'd like to be able to set an optional value to `undefined`. For some internal reasons, that specific value cannot be `null`. Is the above check in react-controlled-form's `composeFieldData` really needed?

**Comment by robinweser** [comment]
Hmm. We need that check as otherwise all values that are not set would be reset to `undefined`. Apart from that, we might especially exclude the `value` field and allow setting `undefined`.

Yet, I don't quite get why you'd not be able to use `null` or sth. else? Could you explain that?

**Comment by dlindenkreuz** [comment]
Already found a workaround, nevermind! Would it still make sense to track this and allow `undefined` values?

**Comment by robinweser** [comment]
From my experience, I'd not really want to allow `undefined` actually.
This is kind of reserved for "unset"
