### ISSUE TITLE
Global validation - marking specific field as invalid

### ISSUE THREAD

**Issue by milanvodicka** [rofrischmann/react-controlled-form#29]
Hi guys,
I'm a little bit lost in validation and I need you advice.
Let's have two fields: given name and family name. I want to make given name required only if the family name is entered. I have global validation function that basically goes like this:

`
const validation  = (data) => !data.familyName.valueu || data.givenName.value
`

The issue here is that givenName field doesn't get invalid, only the whole form do. What is the best way to achieve this behavior?

**Comment by robinweser** [comment]
I can give you an example later, but might take some time.

**Comment by robinweser** [comment]
This should now be part of the docs if I'm not missing sth. 
Sorry for the long overdue reply.
