### ISSUE TITLE
Bug: buttons or components created by the asReset HoC always trigger the form onSubmit as a side effect

### ISSUE THREAD

**Issue by JZBo** [rofrischmann/react-controlled-form#33]
Hello rofrischmann! 
First of all, allow me to compliment you on this wonderful library. Personally I think it's extremely clear and concise, and hits exactly a sweet spot in power, expressiveness, clarity of design and ease of use, without needing to be everything and more like the huge monolithic titans like redux-forms or react-redux-forms.
I stumbled upon it by chance some weeks ago, and immediately loved it.

That said, I found what seems to be a bug in the reset function.
**Any component created by the asReset helper (for instance, a simple reset button) has what seems to be an unintended side-effect**: 
*While it does reset the form to the initial state, it also triggers the onSubmit function of the Form, thus attempting to submit an empty (or reset) form!*

I have easily reproduced the bug in the 'simple' example as well.
I created a new component Reset.js
```/* @flow */
import React from 'react'
import { asReset } from 'react-controlled-form'

const Reset = ({ resetForm }: { resetForm: Function }) =>
  <button onClick={resetForm}>Reset</button>

export default asReset(Reset)
```

Then, in the index.js, I imported it ad added it to the example page, adding an extra line of console.log to the onSubmit.

```import React from 'react'
import ReactDOM from 'react-dom'
import { Provider } from 'react-redux'
import { Form, mapDataToValues } from 'react-controlled-form'

import Submit from './components/Submit'
import Reset from './components/Reset'
import Input from './components/Input'

import DataDisplay from './DataDisplay'
import store from './store'

function onSubmit({ data, resetForm }) {
  console.log('RCF onSubmit called!');
  alert(JSON.stringify(mapDataToValues(data), null, 2))
  resetForm()
}

const render = () =>
  ReactDOM.render(
    <Provider store={store}>
      <Form formId="simple" onSubmit={onSubmit}>
        <div>
          <h1>Simple Example</h1>
          <br />
          <Input fieldId="firstname" />
          <Input fieldId="lastname" />
          <Submit />
          <Reset />
          <br />
          <DataDisplay />
        </div>
      </Form>
    </Provider>,
    document.getElementById('root')
  )

render()
store.subscribe(render)
```

As you'll be able to see, the result is that after resetting the form, the onSubmit fires anyways.

I tried to a look at the code of your reducers for the `initForm` action, to see if this behaviour was caused by an error for which I could find a solution myself, but unfortunately I didn't see anything that could justify this bug at a first glance.

**Comment by robinweser** [comment]
Hey @JZBo,

Thanks for your very kind feedback! If you like the library, feel free to spread the word ;) 
I am currently working on a new major version with render-props APIs. The HoCs will still be there, but the Form component slightly changed as well. I will try to fix that bug while doing the version bump :) 

Thanks for reporting!
Seems strange what's happening there...

**Comment by robinweser** [comment]
Oh alright, just got it. It's not a bug, but a browser behaviour. 
If there's a button without a type within a `<form>` element, it automatically submits on click or enter.

Try to add `type="reset"` and the issue is gone :o

**Comment by JZBo** [comment]
Thanks for the quick reply! 

I also realized that writing
```
onClick={ (event) => {
  event.preventDefault();
  resetForm();
}
```
also solves the issue. 
My mistake! I thought a solution like this was somehow included in the resetForm() function. 

You might want to consider to either specify it in the docs, or maybe to directly include this in the code of asReset.

I'm thrilled to read about the upcoming update, and I'll look forward to it!
