### ISSUE TITLE
Migration help & request for better documentation for version 3+

### ISSUE THREAD

**Issue by JZBo** [rofrischmann/react-controlled-form#34]
Greetings,

I have seen the update of RCF, and tried to migrate today on a couple of more elaborate forms, however I am completely at loss on several parts.

1) I don't seem to find in the documentation what are the supposed input parameters of the Form render function. (Its render props, if I am correct in the terminology)
Field is documented as passing the same props as before. But what about Form?
In the examples there are some clues, for instance:
```render={({ reset, data }) => ```
But is it all? Is there anything else? Does it pass down state as well? Does it follow the callback shape?

2) How can I pass additional properties to my custom components? 
With version up to v2 it was extremely easy to pass them, given that the HoC asField passed them down the hierarchy. Now I'm at loss on what I am supposed to do
For instance, let's suppose I had a custom input component which used among the props some extra ones 'customOne' and 'customTwo'.
I could simply do: 
```
const myField = (props) => {
 const { updateField, value, isEnabled, isValid, customOne, customTwo, ...everythingElse } = props;
// All the various functions, e.g: myChangeHandler
return (
<div>
 <MyCustomInput customOne={customOne}, onChange={myChangeHandler}>
 <MyValidatorMessage customTwo={customTwo}, isValid={isValid}>
</div>
)
}
```
Then it was very simple to simply call 
```
const InputName = asField(myField);
```
And to render it as:
```
<InputName
  fieldId="name"
  customOne='100px'
  customTwo='Invalid Input!'
/>
```

Ok, how am I supposed to obtain the same results in version 3?
As far as I can see from the docs, Field does not act as a proxy and does not pass on any extra props received down the hierarchy.
(Basically, I'm trying to do what I could do CreateComponentWithProxy in react-fela, to use an example of another awesome repo of yours).

The only solution that came into mind was to create a wrapper for the RCF Form, pass to that wrapper any additional props, and have the RCF Form use them in its render function, but it looks like it could grow very quickly in terms of length if you have non-trivial forms with a dozen of fields.

Suggestions?

3) Almost every time I try to do anything I run into an error, for instance, even if I try to render an empty form like:
```			
<Form
	formId="anotherId"
	render={({ reset, data }) => (
		<form
			onSubmit={() => {
				alert(JSON.stringify(mapDataToValues(data), null, 2));
				reset()
			}}>
			<div
				className={this.props.className}
				>
				<h1>Simple Example</h1>
				<span>Whether I put a Field or not here I get the same results</span>
				<br />
				<button>Submit</button>
				<br />
			</div>
		</form>
	)}
/>
```

Then I get....

**connectAdvanced.js:241 Uncaught TypeError: Cannot read property 'anotherId' of undefined**
    at Function.mapStateToProps [as mapToProps] (form.js:20)
    at mapToPropsProxy (wrapMapToProps.js:43)
    at Function.detectFactoryAndVerify (wrapMapToProps.js:52)
    at mapToPropsProxy (wrapMapToProps.js:43)
    at handleFirstCall (selectorFactory.js:26)
    at pureFinalPropsSelector (selectorFactory.js:74)
    at Object.runComponentSelector [as run] (connectAdvanced.js:26)
    at Connect.initSelector (connectAdvanced.js:178)
    at new Connect (connectAdvanced.js:119)
    at constructClassInstance (react-dom.development.js:6355)
mapStateToProps @ form.js:20
mapToPropsProxy @ wrapMapToProps.js:43
detectFactoryAndVerify @ wrapMapToProps.js:52
mapToPropsProxy @ wrapMapToProps.js:43
handleFirstCall @ selectorFactory.js:26
pureFinalPropsSelector @ selectorFactory.js:74
runComponentSelector @ connectAdvanced.js:26
initSelector @ connectAdvanced.js:178
Connect(Form) @ connectAdvanced.js:119
constructClassInstance @ react-dom.development.js:6355
updateClassComponent @ react-dom.development.js:7839
beginWork @ react-dom.development.js:8225
performUnitOfWork @ react-dom.development.js:10224
workLoop @ react-dom.development.js:10288
callCallback @ react-dom.development.js:542
invokeGuardedCallbackDev @ react-dom.development.js:581
invokeGuardedCallback @ react-dom.development.js:438
renderRoot @ react-dom.development.js:10366
performWorkOnRoot @ react-dom.development.js:11014
performWork @ react-dom.development.js:10967
batchedUpdates @ react-dom.development.js:11086
batchedUpdates @ react-dom.development.js:2330
dispatchEvent @ react-dom.development.js:3421

Any ideas?

**Comment by robinweser** [comment]
Oh my, I am sorry. I forgot to update the Form component documentation :o 

Check out the following code line for a quick overview:
https://github.com/rofrischmann/react-controlled-form/blob/master/modules/components/Form.js#L96

That's all we're passing down - literally everything you need to render the same stuff as before.

I also forgot to mention that the reducer was transformed, you now need to use `combineReducers({ ...formReducer })` instead of `combineReducers({ form: formReducer })`.

Passing down others props is pretty simple:
```javascript
const myField = ({ fieldId, customOne, customTwo, ...everythingElse }) => (
  <Field fieldId={fieldId} render={({ value, isEnabled, isValid, updateField }) => {
    // prepare your stuff    

    return (
      <div>
        <MyCustomInput customOne={customOne} onChange={myChangeHandler}>
        <MyValidatorMessage customTwo={customTwo} isValid={isValid}>
      </div>
    )}
  )} />
)
```

The beauty is that we can now explicitly pass down everything and down have implicit logic within the HoC.

**Comment by JZBo** [comment]
Ok, great! Thanks for the answer! That solves two of the doubts :) - problem 1 and problem number 3, since that was related to the store setup.
I suppose that it also means that I should not use as formId any identifier that might be used by another reducer?

What about problem number 2 though? Any input?

**Comment by robinweser** [comment]
I just updated the above comment. You can still use any identifier, but the reducer now is not assigned to the key `form` but as `__CONTROLLED_FORM`. This helps to prevent conflicts in the first hand, but all your identifier still apply within the __CONTROLLED_FORM key, not the overall store.

Thanks for ally our feedback btw, I will update the docs as soon as possible :)

**Comment by JZBo** [comment]
Good, thanks a lot for all the clarifications!
