### ISSUE TITLE
onSubmit prop of Form component - absent in version 3.0? Discrepancy between documentation and implementation?

### ISSUE THREAD

**Issue by JZBo** [rofrischmann/react-controlled-form#36]
Greetings again!

I have found another issue related to version 3.0, hopefully you won't mind too much.
According to the docs, the Form component should have the quite fundamental 'onSubmit' prop, a function that would be called on form submit, whose first parameter matches the callback shape.
That would be coherent with versions 1.x and 2 of RCF.

Surprisingly, though, this prop is completely absent from the Component.
Examining the modules/component/Form.js file, there seems to be no trace of it. Not only that, a quick search of 'onSubmit' on the modules directory of the repo seems to find no matches.
In the examples it is also not used.

Aside from the mismatch between docs and code, is this absence by design or is it something that got accidentally cut? It seems like an heavy absence from the module.

**Comment by robinweser** [comment]
Yeah, as mentioned before, I forgot to update the Form docs.
The is no submit method at all, because you can directly use the onSubmit on the renderer `<form>` DOM element instead - without any implicit logic.

I will try to update that as soon as possible.

**Comment by JZBo** [comment]
I understand the reasoning, thanks for the detailed explanation. 

If I might make a very circumstantial point in favour of having the onSubmit prop bound to the Form component: It was useful in case you had the submit button located elsewhere in the DOM.
For instance, let's suppose the submit button for the form is in a confirmation modal, which is rendered and mounted by the modal library outside the `<form>` HTML element. 
It these cases, using a `<button type="submit">` won't work, because the button won't find the parent `<form>`, while using the previous "asSubmit" HoC with the "onSubmit" property allowed it to function anyways.

Not that it's unsolvable: you just have to explicitly declare and bind the formSubmit handling function somewhere, and pass it to the modal component setting the button type to 'button' instead of 'submit'.
Still, it's just slightly less clear.

**Comment by robinweser** [comment]
I am planning to add 2 more components that enable that exact behaviour. Having data/state/submit/reset, well even <Field> itself in a completely different tree (even other forms) and still bound to the defined form.

**Comment by JZBo** [comment]
It's a great news, I'll look forward to those
