### ISSUE TITLE
[Likely bug] Sending an updateField with {value:null} has no effect, and the field is not updated

### ISSUE THREAD

**Issue by JZBo** [rofrischmann/react-controlled-form#37]
Greetings.

I noticed another issue with this excellent module, which seems to be more a bug or an unintended side-effect rather than something working as intended.

using the updateField action creator with a payload containing a { value: null } results in the UPDATE_FIELD action being completely ignored by the reducer, and the value stays the same in the form store slice.

As far as I have seen, the culprit is here: 
https://github.com/rofrischmann/react-controlled-form/blob/master/modules/model/reducers/updateField.js, at line 26, which uses: 
https://github.com/rofrischmann/react-controlled-form/blob/master/modules/model/composeData.js, at line 13.

A brief word on the use case of sending an UPDATE_FIELD to reset the value to null:
I am using it to reset specific fields in the form.
For instance, a field with a mutable datatype (which might be either a number or a string). If i want to reset it to a 'pristine' status, then null seems to be the most correct option for its value.

At the moment I would need to send an updateField({ value: '' }), which however seems more forced and less semantically correct than having a nullable value property in the field data. After all, 0, '', false, null, undefined and so on all have slightly different meanings.

**Comment by robinweser** [comment]
Hmm, there was a reason why we disallowed both `undefined` and `null` but I can't really get it again :/ I will reconsider that with the next iteration.

**Comment by JZBo** [comment]
Thanks for the kind answer. 
I would beg you to examine the possibility to allow it, especially for ```null``` instead of undefined. 
I think there are reasonable use cases to warrant it: after all, null has a legitimate use in javascript

One example is above, where a field is of a variable datatype (e.g: there is a toggle in the form that changes the type of input), I feel it makes more sense resetting it to null.
Other cases might be for integration with other libraries. For instance, and if I recall correctly, ```react-select``` sends a null value for its option if its ```isClearable``` toggle is switched on. 
Or you might be wanting to initialize form data from a remote data source, which might have fields with 'nullable' values.

Nothing that cannot be overcome, mind you, especially once it's known. It's just it feels a bit redundant to write checks and care for that specific case.
